# ===================================================================
# Spring Boot Configuration for the prod profile
# ===================================================================

# SERVER
server:
  error:
    include-exception: true # Include the "exception" attribute.
    include-stacktrace: always # When to include a "stacktrace" attribute.
    whitelabel.enabled: true

# LOGGING
logging:
  level:
    root: INFO

# SPRING
spring:
  config:
    import:
      - 'aws-parameterstore:/mania/api-server_prod/'
  jackson:
    serialization:
      indent_output: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# DATABASE
mania:
  master:
    datasource:
      url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
      hikari:
        minimum-idle: 15
        maximum-pool-size: 25
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: none
  maximum-jdbc-thread-pool-size: