# ===================================================================
# Spring Boot Configuration for the default profile
# ===================================================================

# SERVER
server:
  port: 8080
  http2:
    enabled: true
  shutdown: graceful # timeout configuration property : spring.lifecycle.timeout-per-shutdown-phase

logging:
  level:
    root: INFO

# SPRING
spring:
  config:
    import:
      - classpath:/config/balancemania-config.yml
  lifecycle:
    timeout-per-shutdown-phase: 5s # format : https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-conversion-duration
  application:
    name: balance-mania-api
  data:
    redis:
      repositories:
        enabled: false
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:testKey}
        secret-key: ${AWS_SECRET_ACCESS_KEY:secretKey}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${AWS_S3_BUCKET:bucket}
      stack:
        auto: false

# DOCS
springdoc:
  swagger-ui:
    operations-sorter: alpha
  model-and-view-allowed: true
  packages-to-scan: com.balancemania.api

# DATABASE
mania:
  master:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 10
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibrenate.jdbc.batch_size: 50
      hibernate.jdbc.batch_versioned_data: true
      hibernate.jdbc.time_zone: Asia/Seoul
      hibernate.hbm2ddl.auto: none
    show-sql: false
    database: mysql
    open-in-view: false

# AUTH
auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-exp: ${JWT_ACCESS_EXP}
    refresh-exp: ${JWT_REFRESH_EXP}

# OAUTH
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    admin-key: ${KAKAO_ADMIN_KEY}

oauth-url:
  kakao:
    withdraw-callback-url: ${KAKAO_WITHDRAW_CALLBACK_URL}
    unlink-url: ${KAKAO_UNLINK_URL}
    user-info-url: ${KAKAO_USER_INFO_URL}
    authorize-url: ${KAKAO_AUTHORIZE_URL}
    token-url: ${KAKAO_TOKEN_URL}
    kauth-url: ${KAKAO_KAUTH_URL}
    kapi-url: ${KAKAO_KAPI_URL}
    redirect-url: ${KAKAO_REDIRECT_URL}

media-pipe:
  url: ${MEDIAPIPE_IMG_ANALYSIS_URL}

